### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by winkerbie** [horsicq/x64dbg-Plugin-Manager#21] opened 2022-06-14 12:18 UTC
Hi I cant seem to update any of the plugins or the core x64dbg.
It recognises plugins and the core need updating, but when I click it, the downloading screen pops up but there are not files downloaded??

Also what does it mean by x64dbg directory? Is that /releases (which contained \x64 and \x32 folder?

Thanks

**Comment by horsicq** [comment] 2022-06-14 12:20
Thanks a lot for the bugreport!

I will take a look.

**Comment by winkerbie** [comment] 2022-06-14 12:22
![image](https://user-images.githubusercontent.com/24724296/173576085-13cdbd0b-5697-4ab4-95da-6151ff1b3da8.png)

**Comment by warp123** [comment] 2022-11-28 06:13
Any news about the issue? Any thoughts how to fix it maybe?

**Comment by horsicq** [comment] 2022-11-28 16:02
Hello. It will be fixed a little later.

**Comment by Truevoxdei** [comment] 2023-02-19 11:28
> Same problem here. In my case I can see some zip files downloaded inside /Data/Modules, but they are not copied inside x64dbg plugin folder. Same happens with core files. Inside the zip files there is only the .json file. The "fles" folder with the plugins is missing

Yes, I has too some problem with ver. 0.5. No download correct and no unpack to destination dir (..release\x32\plugins\ or ...release\x64\plugins\
![plug](https://user-images.githubusercontent.com/24456843/219945051-ae7c14d6-e80e-4d72-86b4-969a110e13e7.jpg)

**Comment by ParkerDandrow** [comment] 2023-02-23 06:44
Ever gonna fix that, or what buddy?

**Comment by horsicq** [comment] 2023-02-23 07:15
> Ever gonna fix that, or what buddy?

It works on my machine. I do not know what I should fix. :(

**Comment by warp123** [comment] 2023-02-23 08:29
> Same problem here. In my case I can see some zip files downloaded inside /Data/Modules, but they are not copied inside x64dbg plugin folder. Same happens with core files.
> Inside the zip files there is only the .json file. The "fles" folder with the plugins is missing

The problem is described in my earlier post. 
The zip file downloaded is missing the Files folder. Just the Jason file. 

You should check the procedure that creates of fetches the zip file. 

I can help you on the debugging if you like

**Comment by horsicq** [comment] 2023-02-23 09:04
> I can help you on the debugging if you like

Oh. Thank you! I will create in 1-2 days a beta version of the program. Could you please check it?

**Comment by horsicq** [comment] 2023-02-23 10:15
https://github.com/horsicq/x64dbg-Plugin-Manager/releases/tag/Beta

**Comment by Truevoxdei** [comment] 2023-02-23 23:48
[data.zip](https://github.com/horsicq/x64dbg-Plugin-Manager/files/10819394/data.zip)
Not yet correct work. Empty zip's plugins archive when download. No folder Files, only json. My OS English Microsoft Windows [Version 10.0.22000.1574]

**Comment by horsicq** [comment] 2023-02-24 00:07
> [data.zip](https://github.com/horsicq/x64dbg-Plugin-Manager/files/10819394/data.zip)
> Not yet correct work. Empty zip's plugins archive when download. No folder Files, only json. My OS English Microsoft Windows [Version 10.0.22000.1574]

Thanks! I will take a look.

**Comment by horsicq** [comment] 2023-02-24 00:44
> [data.zip](https://github.com/horsicq/x64dbg-Plugin-Manager/files/10819394/data.zip)
> Not yet correct work. Empty zip's plugins archive when download. No folder Files, only json. My OS English Microsoft Windows [Version 10.0.22000.1574]
I tested on Windows 10 and fixed some bugs.
I reuploaded the Beta version. Please check it
https://github.com/horsicq/x64dbg-Plugin-Manager/releases/tag/Beta

**Comment by warp123** [comment] 2023-02-25 08:16
I thing that the Beta works fine in my first test machine. I will further test it. I was planning to review the source this weekend but as long as it works I think there is no point.

**Comment by warp123** [comment] 2023-02-25 08:33
UPDATE: Of all the plugins the one called ClawSearch is still missing the files inside the zipped archive

**Comment by Truevoxdei** [comment] 2023-02-25 08:43
> > [data.zip](https://github.com/horsicq/x64dbg-Plugin-Manager/files/10819394/data.zip)
> > Not yet correct work. Empty zip's plugins archive when download. No folder Files, only json. My OS English Microsoft Windows [Version 10.0.22000.1574]
> 
> I tested on Windows 10 and fixed some bugs. I reuploaded the Beta version. Please check it https://github.com/horsicq/x64dbg-Plugin-Manager/releases/tag/Beta

Now plug'n manage is work good. But as wrote user wrap123, plug'n manage not work correct with ClawSearch and ASLR-Removal.x64dbg. 
[modules.zip](https://github.com/horsicq/x64dbg-Plugin-Manager/files/10830616/modules.zip)

**Comment by horsicq** [comment] 2023-02-25 08:52
@warp123 and @Truevoxdei Thanks for the testing! You really helped me a lot! I will fix the small things and make a release version next week.

**Comment by horsicq** [comment] 2023-03-03 08:10
Fixed

**Closed by horsicq** 2023-03-03 08:10 UTC
